name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Generate Snake
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
            dist/github-contribution-grid-snake-dark.svg?color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353

      # 3. Commit generated files
      - name: Commit Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist"
          message: "chore: update contribution snake"
